apiVersion: v1
kind: Secret
metadata:
  name: usuarios-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=fcg-sqlserver;Database=FCG_Usuarios;User Id=sa;Password=FCG@Pass123;TrustServerCertificate=True"
  RabbitMQ__Senha: "guest"